name: run on pull request
on : 
    pull_request:
     types: opened
    workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        run: echo 'anil sidhu'
      - name: bye
        run: echo "bye bye"

